#!/bin/sh
# author: notsobad
# Fix rtf problem generated by openjade.
set -x

rtf=$1
tmp=/tmp/$$.rtf

# fix the chinese problem
cat > $tmp <<EOF
{\rtf1\ansi\ansicpg936\uc1\deff0\deflang1033\langfenp2052
EOF

sed -e '1,/^}$/d' $rtf >> $tmp

# fix the toc number problem, then all the number goes to empty.
sed -i 's/{\\fldrslt 000}/{\\fldrslt .}/g' $tmp
mv $tmp $rtf
